#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    accelerometerX, sensorAccelerometer)
#pragma config(Sensor, in2,    accelerometerY, sensorAccelerometer)
#pragma config(Sensor, in3,    gyroSensor,     sensorGyro)
#pragma config(Sensor, in4,    flyBattery,     sensorAnalog)
#pragma config(Sensor, dgtl1,  brakePistons,   sensorDigitalOut)
#pragma config(Sensor, dgtl2,  lockPistons,    sensorDigitalOut)
#pragma config(Sensor, dgtl3,  deployerPiston, sensorDigitalOut)
#pragma config(Sensor, dgtl4,  laser,          sensorDigitalOut)
#pragma config(Sensor, dgtl5,  yellowLED,      sensorDigitalOut)
#pragma config(Sensor, dgtl6,  greenLED,       sensorDigitalOut)
#pragma config(Sensor, dgtl7,  redLED,         sensorDigitalOut)
#pragma config(Sensor, dgtl8,  ballCounter,    sensorTouch)
#pragma config(Sensor, dgtl9,  ,               sensorDigitalOut)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           roller,        tmotorVex393TurboSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           topLeftLauncher, tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_4)
#pragma config(Motor,  port3,           bottomLeftLauncher, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           topRightLauncher, tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port5,           bottomRightLauncher, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           rightback,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rightfront,    tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port8,           leftback,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           leftfront,     tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port10,          chain,         tmotorVex393TurboSpeed_HBridge, openLoop, encoderPort, I2C_5)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
bool userControl = false;
bool competitionMode = false;
bool autoFunctionsDisabled = false;
#pragma platform(VEX)
#pragma competitionControl(Competition)
#include "cool.c"
#include "PID_ValuesMotorRPM.h"
#include "FlyWheelAndIntake.h"
#include "DriveAndPneumatics.h"
#include "Autonomous.h"
#include "SpeakerAndLCD.h"
void pre_auton()
{
	SensorValue[laser] = 1;
	bStopTasksBetweenModes = false;
	SensorType[in3] = sensorNone;
	wait1Msec(1000);
	SensorType[in3] = sensorGyro;
	wait1Msec(1000);
	startTask(LCD);
}
task autonomous()
{
	userControl = false;
	SensorValue[laser] = 0;
	competitionMode = true;
	runAuto(chosenAuto);
}
task usercontrol()
{
	userControl = true;
	if(getTaskState(autonomous) == taskStateRunning)
		stopTask(autonomous);
    if(getTaskState(flyWheelPower) == taskStateRunning)
       stopTask(flyWheelPower);
	SensorValue[laser] = 0;

	autoTuning = false;
	rpmGoal = rpmHigh;
	clearDebugStream();

	if(getTaskState(LCD) == taskStateStopped)
		startTask(LCD);
	if(getTaskState(calculateAccelBiases) == taskStateStopped)
		startTask(calculateAccelBiases);
	if(autoTuning) {
		startTask(autoPIDTuner);
	} else {
		if(getTaskState(flyWheelPower) == taskStateStopped)
			startTask(flyWheelPower);
		if(getTaskState(flyWheelControl) == taskStateStopped)
			startTask(flyWheelControl);
		if(getTaskState(shotTracker) == taskStateStopped)
			startTask(shotTracker);
	}
	if(getTaskState(drive) == taskStateStopped)
		startTask(drive);
	if(getTaskState(positionTracker) == taskStateStopped)
		startTask(positionTracker);
	if(getTaskState(pneumatics) == taskStateStopped)
		startTask(pneumatics);
	if(getTaskState(speaker) == taskStateStopped)
		startTask(speaker);
	if(getTaskState(intake) == taskStateStopped)
		startTask(intake);
	//if(getTaskState(automaticBrakingSystem) == taskStateStopped)
		//startTask(automaticBrakingSystem);
}
